Try to suppress coveralls errors

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -47,7 +47,7 @@ jobs:
             # Coveralls was failing for pull requests
             # I think there's a problem with the integration in github?
             if [[ $CIRCLE_BRANCH == master ]]; then
-              npm run coveralls
+              npm run coveralls || echo "Coveralls failed!"
             else
               echo "Not running coveralls (not master branch)"
             fi
